# ==============================================================================
# Script title: hierBAPS clustering from Parsnp informative core-genome sites
# Author: Silvana Yalú Cristo Martínez
# Creation date: 2026-05-13
# Last update: 2026-05-13
#
# Description:
# This script prepares a Parsnp PHYLIP core-genome alignment for hierBAPS
# clustering. It removes non-informative alignment columns, writes the filtered
# informative-site alignment as FASTA, and runs hierBAPS to infer population
# structure.
#
# The script:
# - Loads the Parsnp PHYLIP alignment
# - Filters the alignment to keep informative sites only
# - Writes the filtered alignment in FASTA format
# - Runs hierBAPS with two clustering levels
# - Saves both cluster assignments and the complete hierBAPS object
#
# Requirements:
# - R packages: rhierbaps, ape
# - Parsnp PHYLIP alignment generated by PGDSpider
# - Rscript or an interactive R session
# ==============================================================================


# ==============================================================================
# LOAD REQUIRED PACKAGES
# ==============================================================================

library(rhierbaps)
library(ape)


# ==============================================================================
# DEFINE INPUTS AND OUTPUT DIRECTORY
# ==============================================================================

alignment_file <- "/export/space3/users/silvanac/Abaumannii_ChromArch/results/parsnp/parsnp.phy"

outdir <- "/export/space3/users/silvanac/Abaumannii_ChromArch/results/hierbaps"
dir.create(outdir, recursive = TRUE, showWarnings = FALSE)


# ==============================================================================
# LOAD PARSNP ALIGNMENT
# ==============================================================================

alignment <- ape::read.dna(
  alignment_file,
  format = "sequential"
)

cat("Dimensiones originales:\n")
print(dim(alignment))


# ==============================================================================
# IDENTIFY INFORMATIVE SITES
# ==============================================================================

alignment_char <- as.character(alignment)
alignment_char <- toupper(alignment_char)

informative_sites <- apply(alignment_char, 2, function(col) {
  col2 <- col[col != "-" & col != "N"]
  length(unique(col2)) > 1
})

cat("Sitios informativos:\n")
print(sum(informative_sites))


# ==============================================================================
# FILTER ALIGNMENT TO INFORMATIVE SITES
# ==============================================================================

alignment_inf <- alignment[, informative_sites]

cat("Dimensiones filtradas:\n")
print(dim(alignment_inf))


# ==============================================================================
# WRITE FILTERED ALIGNMENT AS FASTA
# ==============================================================================

filtered_fasta <- file.path(outdir, "parsnp_informative_sites.fasta")

ape::write.dna(
  alignment_inf,
  file = filtered_fasta,
  format = "fasta",
  nbcol = -1,
  colsep = ""
)

cat("FASTA filtrado guardado en:\n")
print(filtered_fasta)


# ==============================================================================
# LOAD FILTERED ALIGNMENT FOR HIERBAPS
# ==============================================================================

snp_matrix <- load_fasta(filtered_fasta)

cat("Objeto cargado con load_fasta\n")


# ==============================================================================
# RUN HIERBAPS
# ==============================================================================

hb <- hierBAPS(
  snp_matrix,
  max.depth = 2,
  n.pops = 20
)


# ==============================================================================
# SAVE HIERBAPS OUTPUTS
# ==============================================================================

write.csv(
  hb$partition.df,
  file = file.path(outdir, "hierbaps_clusters.csv"),
  row.names = FALSE
)

saveRDS(
  hb,
  file = file.path(outdir, "hierbaps_result.rds")
)
